version: '3'
services:
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
  ts3db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example1Passwd
      MYSQL_DATABASE: teamspeak
    volumes:
      - ./drives/ts3db:/var/lib/mysql
  ts3Server:
    image: teamspeak:3.4
    restart: always
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: ts3db
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: example1Passwd
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    depends_on: 
      - ts3db
    volumes:
      - ./drives/ts3server:/var/ts3server
  analyticsDb:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: always
    ports:
      - 1433:1433
    environment: 
      ACCEPT_EULA: Y
      SA_PASSWORD: example1Passwd
      MSSQL_PID: Express
    volumes: 
      - ./drives/analyticsDb:/var/opt/mssql
  analytics-service:
    build: ./teamspeak-analytics-api
    restart: always
    ports: 
      - 80:80
    depends_on: 
      - analyticsDb
      - ts3Server
    environment: 
      MSSQL_Server_Address: analyticsDb
      MSSQL_Server_User: sa
      MSSQL_Server_Password: example1Passwd
      MSSQL_Server_Database_Name: TeamspeakAnalytics
      TS3_Address: ts3Server
      TS3_User: serveradmin
      TS3_Password: VHvakrGZ
